// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 16/5/2025, 2:35:04 p. m.
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/varga/OneDrive/Documents/GitHub/tiendadeportiva.vue/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/varga/OneDrive/Documents/GitHub/tiendadeportiva.vue/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/varga/OneDrive/Documents/GitHub/tiendadeportiva.vue/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/varga/OneDrive/Documents/GitHub/tiendadeportiva.vue/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/varga/OneDrive/Documents/GitHub/tiendadeportiva.vue/plugins/**/*.{js,ts,mjs}","C:/Users/varga/OneDrive/Documents/GitHub/tiendadeportiva.vue/composables/**/*.{js,ts,mjs}","C:/Users/varga/OneDrive/Documents/GitHub/tiendadeportiva.vue/utils/**/*.{js,ts,mjs}","C:/Users/varga/OneDrive/Documents/GitHub/tiendadeportiva.vue/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/varga/OneDrive/Documents/GitHub/tiendadeportiva.vue/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/varga/OneDrive/Documents/GitHub/tiendadeportiva.vue/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/varga/OneDrive/Documents/GitHub/tiendadeportiva.vue/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;